---
root: true

env:
  browser: true
  es2021: true

plugins:
  - vue
  - '@typescript-eslint'
  - eslint-plugin-tsdoc

extends:
  - airbnb-base
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:vue/vue3-essential
  - prettier
  - prettier/@typescript-eslint
  - prettier/prettier
  - prettier/vue

parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 12
  sourceType: module
  parser: '@typescript-eslint/parser'
  parserOptions:
    project: ./tsconfig.json

rules:
  # Replace eslint rules with @typescript-eslint
  no-unused-vars: off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  # Manage order of imports
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
      pathGroups:
        - pattern: einstein
          group: external
      newlines-between: always
      alphabetize:
        order: asc
        caseInsensitive: true
  # Force to use 'einstein' as api imports
  no-restricted-imports:
    - error
    - paths:
        - name: '@/api'
          message: Please import from 'einstein' instead.
      patterns:
        - '@/api/*'

  array-bracket-spacing:
    - error
    - always
  class-methods-use-this: off
  import/extensions:
    - error
    - never
    - ignorePackages: true
      pattern:
        vue: always
  import/newline-after-import: off # prevent collision with semi-style: first
  indent:
    - warn
    - tab
  max-classes-per-file: off
  no-tabs: off
  semi:
    - error
    - never
    - beforeStatementContinuationChars: always
  semi-style:
    - error
    - first
  tsdoc/syntax: warn

settings:
  import/core-modules:
    - electron
  import/internal-regex: '^@/'
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
        - .vue
      moduleDirectory:
        - node_modules
        - src
    alias:
      extensions:
        - .ts
        - .js
        - .vue
      map:
        - ['@', './src']
        - ['einstein', './src/api']
