---
root: true

env:
  browser: true
  es2021: true

plugins:
  - vue
  - '@typescript-eslint'

extends:
  - airbnb-base
  - plugin:vue/vue3-essential
  - plugin:@typescript-eslint/eslint-recommended

parser: vue-eslint-parser
parserOptions:
  ecmaVersion: 12
  sourceType: module
  parser: '@typescript-eslint/parser'
  parserOptions:
    project: ./tsconfig.json

rules:
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
  array-bracket-spacing:
    - error
    - always
  class-methods-use-this: off
  import/extensions:
    - error
    - never
    - ignorePackages: true
      pattern:
        vue: always
  import/newline-after-import: off # prevent collision with semi-style: first
  indent:
    - warn
    - tab
  max-classes-per-file: off
  no-tabs: off
  no-unused-vars: off # use typescript rule
  semi:
    - error
    - never
    - beforeStatementContinuationChars: always
  semi-style:
    - error
    - first
settings:
  import/core-modules:
    - electron
  import/resolver:
    node:
      extensions:
        - .js
        - .ts
        - .vue
      moduleDirectory:
        - node_modules
        - src
    alias:
      extensions:
        - .ts
        - .js
        - .vue
      map:
        - [ '@', './src' ]
