---
env:
  browser: false
  node: true

rules:
  # Disable usage of electron
  no-restricted-imports:
    - error
    - paths:
        - electron
        - name: '@/api'
          message: Please import from 'einstein' instead.
      patterns:
        - electron/*
        - '@/api/*'
