/* eslint-disable import/prefer-default-export */

// environment variables that we allow to pass down to sub processes
export const KEEP_ENV = new Set([
	'COLORFGBG',
	'COLORTERM',
	'DBUS_SESSION_BUS_ADDRESS',
	'DISPLAY',
	'EDITOR',
	'GTK_IM_MODULE',
	'HOME',
	'KDEDIR',
	'LANG',
	'LANGUAGE',
	'LC_ALL',
	'LC_CTYPE',
	'LOGNAME',
	'MAIL',
	'PATH',
	'PWD',
	'QTDIR',
	'QT_IM_MODULE',
	'QT_IM_SWITCHER',
	'SHELL',
	'SHLVL',
	'SSH_AUTH_SOCK',
	'SUDO_COMMAND',
	'SUDO_GID',
	'SUDO_UID',
	'SUDO_USER',
	'TERM',
	'USER',
	'XAPPLRESDIR',
	'XAUTHORITY',
	'XDG_SESSION_COOKIE',
	'XFILESEARCHPATH',
	'XMODIFIERS',
	'XUSERFILESEARCHPATH',
	'_',
])

export const ICON_EXT = new Set([
	'.png',
	'.xpm',
	'.svg',
])
