name: Build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Change diff
        run: git --no-pager show -m "$GITHUB_SHA" --color

      - name: Build
        shell: bash
        run: |
          npm --version
          npm ci
          pushd plugins/desktop && npm ci; popd
          npm run lint
          npm run build
